<?php

namespace AppBundle\Repository;

/**
 * NominesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NominesRepository extends \Doctrine\ORM\EntityRepository
{
}
